name: Backend CI

on:
  pull_request:
    branches: ["main"]
    paths: ["backend/**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          version: 2025.12.13
          install: true
          working_directory: backend
          experimental: true

      - name: Go Format
        run: go fmt ./...

      - name: GolangCI Lint
        run: golangci-lint run

      - name: Start MySQL Container
        run: docker compose up -d --wait

      - name: echo env1
        run: echo $APP_ENV

      - name: echo env2
        env:
          APP_ENV: ci
        run: echo $APP_ENV

      - name: Run Tests
        env:
          APP_ENV: ci
        run: go test -v ./...
